name: chat_me
description: "Chat.Me is an advanced messaging application developed using Flutter and Firebase. Originally created as part of The Complete Flutter Development Bootcamp, by Dr. Angela Yu and App Brewery. This project has been significantly enhanced to showcase a range of features including user registration, authentication, login, and direct messaging capabilities. Leveraging Firebase's robust backend services, Chat.Me offers a seamless and interactive messaging experience."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.8.0
  cloud_firestore: ^4.9.0
  modal_progress_hud_nsn: ^0.4.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  flutter_image_compress: ^2.1.0
  flutter_native_splash: ^2.3.10
  awesome_notifications_core: ^0.9.0 # <~ always ensure to use the latest version
  awesome_notifications: any # <~ this version is managed by awesome_notifications_core package

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
